/* ============================================================
   ISEdA 國際特殊教育協會 — 多語言切換 (繁/简/EN)
   用法：在元素上加 data-i18n="字典鍵名"，applyLang 會自動替換文字
   data-i18n-html = 允許內含 HTML 標籤（如 <strong>）
   data-i18n-placeholder = 替換輸入框 placeholder
   data-i18n-title = 替換 <title>
   ============================================================ */

const I18N = {
  /* ============ 繁體中文（預設） ============ */
  'zh-Hant': {
    // 品牌與導覽
    'brand.zh': '國際特殊教育協會',
    'brand.sub': 'International Special Education Association',
    'nav.home': '首頁',
    'nav.about': '關於我們',
    'nav.events': '活動專區',
    'nav.knowledge': '專業知識庫',
    'nav.members': '會員專區',
    'nav.partners': '合作洽談',
    'nav.login': '加入我們',
    'title.join': '加入我們 - ISEdA 國際特殊教育協會',
    'join.hero.title': '加入我們',
    'join.hero.sub': '填寫會員登記表單，加入國際特殊教育協會的共融社群。',
    'join.breadcrumb': '加入我們',
    'join.form.title': '會員登記表單',
    'join.form.sub': '請在下方填寫表單；您的資料會透過 Google Forms 安全提交。',
    'join.form.unavailable': '您的瀏覽器無法顯示內嵌表單。',
    'join.form.open': '無法使用內嵌表單？在新視窗開啟會員登記表單',
    'crumb.home': '首頁',
    'crumb.about': '關於我們',
    'crumb.events': '活動專區',
    'crumb.knowledge': '專業知識庫',
    'crumb.members': '會員專區',
    'crumb.partners': '合作洽談',
    'title.index': 'ISEdA 國際特殊教育協會 - 首頁',
    'title.about': '關於我們 - ISEdA 國際特殊教育協會',
    'title.events': '活動專區 - ISEdA 國際特殊教育協會',
    'title.knowledge': '專業知識庫 - ISEdA 國際特殊教育協會',
    'title.members': '會員專區 - ISEdA 國際特殊教育協會',
    'title.partners': '合作洽談 - ISEdA 國際特殊教育協會',

    // 頁尾
    'footer.newsletter.title': '✉️ 訂閱最新消息',
    'footer.newsletter.desc': '填寫電郵，即可免費訂閱我們的特教文章、活動通知與會員資訊。',
    'footer.newsletter.placeholder': '輸入您的電子郵件...',
    'footer.newsletter.btn': '立即訂閱 📥',
    'footer.newsletter.success': '✅ 訂閱成功！我們會定期寄送最新消息給您。',
    'footer.contact': '聯絡我們',
    'footer.contact.phone': '📞 電話: +852 xxxx xxxx',
    'footer.contact.address': '📍 地址: 香港九龍某共融社區中心',
    'footer.links': '快速連結',
    'alert.email': '請先輸入有效的電子郵件地址 📧',

    // 首頁
    'index.hero.title': '🌟 連結希望・共融未來',
    'index.hero.sub': '為特殊教育需要 (SEN) 青年、家庭與從業者打造的國際共融平台。',
    'index.hero.btn1': '立即免費加入會員 💡',
    'index.hero.btn2': '探索我們的服務 ↗',
    'index.stats.1': 'SEN 青年受惠',
    'index.stats.2': '特教從業者會員',
    'index.stats.3': '合作機構',
    'index.stats.4': '活動與培訓場次',
    'index.about.title': '關於國際特殊教育協會',
    'index.about.p1': 'ISEdA 是一個以香港為基地的國際性非牟利組織，致力於連結特殊教育需要 (SEN) 青年、家庭、特教從業者與社會各界的橋樑。',
    'index.about.check1': '提供 SEN 青年升學、職訓與就業一條龍支援',
    'index.about.check2': '推動特教從業者專業培訓與國際認證',
    'index.about.check3': '陪伴家長與照顧者，推廣共融教育理念',
    'index.about.check4': '攜手企業落實 ESG，打造共融友善職場',
    'index.about.btn': '了解更多 →',
    'index.portals.title': '我們的服務對象',
    'index.portals.sub': '無論您是青年、從業者、家長，或是想一同推動共融的機構，我們都有專屬的服務與資源。',
    'index.portals.youth.title': '🙋‍♂️ SEN 青年',
    'index.portals.youth.desc': '提供升學規劃、職業培訓、實習機會、就業配對、職場適應支援及領袖培育。',
    'index.portals.youth.link': '尋求支援 →',
    'index.portals.teacher.title': '🧑‍🏫 特教從業者',
    'index.portals.teacher.desc': '提供專業培訓、國際證書課程資訊、學術資源共享與專業交流平台。',
    'index.portals.teacher.link': '專業培訓 →',
    'index.portals.parents.title': '👨‍👩‍👦 家長與照顧者',
    'index.portals.parents.desc': '提供家長支援小組、專業諮詢服務以及共融教育理念推廣，與您並肩同行。',
    'index.portals.parents.link': '獲取協助 →',
    'index.portals.partners.title': '🏢 合作機構',
    'index.portals.partners.desc': '攜手推行 ESG 指標、提高企業社會形象與影響力，共創共融友善職場。',
    'index.portals.partners.link': '合作洽談 →',
    'index.events.title': '🗓️ 即將舉辦的精彩活動',
    'index.events.sub': '從青年聯誼到專業進修，總有一場活動適合您。立即報名，與我們一起成長！',
    'poster': '[活動海報預留區]',
    'index.blog.title': '📖 專業特教知識與資源',
    'index.blog.sub': '由特教專家與實務工作者撰寫的知識庫，涵蓋家長指南、專業培訓與青年成長等主題。',
    'blog.1.tag': '家長指南',
    'blog.1.title': '如何協助 SEN 孩子適應新學期的情緒變化？',
    'blog.1.time': '📝 閱讀時間：5分鐘',
    'blog.2.tag': '專業培訓',
    'blog.2.title': '2026 最新特教證書申請流程與重點解析',
    'blog.2.time': '📝 閱讀時間：8分鐘',
    'blog.3.tag': '青年成長',
    'blog.3.title': '職場適應的 3 個關鍵溝通技巧與實戰分享',
    'blog.3.time': '📝 閱讀時間：6分鐘',
    'index.blog.more': '進入專業知識庫 →',
    'index.testi.title': '💬 會員與夥伴的真實心聲',
    'index.testi.sub': '每一位會員的故事，都是我們持續前進的動力。',
    'index.testi.1.quote': '「透過 ISEdA 的就業配對計劃，我找到了一份真正適合自己的工作，同事們也很願意包容我的步伐。」',
    'index.testi.1.name': '阿傑',
    'index.testi.1.role': 'SEN 青年會員・已成功就業',
    'index.testi.2.quote': '「這裡的家長支援小組讓我覺得不再孤單。孩子上學的情緒問題，終於有人可以一起商量。」',
    'index.testi.2.name': '陳太太',
    'index.testi.2.role': '家長會員・自閉症孩子媽媽',
    'index.testi.3.quote': '「國際證書課程的內容非常扎實，實務案例分享直接帶回教室就能用，對我的教學幫助很大。」',
    'index.testi.3.name': '林老師',
    'index.testi.3.role': '特教從業者・特殊學校教師',
    'index.cta.title': '✨ 準備好加入我們了嗎？',
    'index.cta.desc': '免費成為會員，立即獲得活動優先報名、知識庫資源與最新消息。',
    'index.cta.btn': '立即免費加入 💡',

    // 關於我們
    'about.hero.title': '🏫 關於我們',
    'about.hero.sub': '了解 ISEdA 的使命、願景與發展歷程。',
    'about.who.title': '我們是誰？',
    'about.who.p1': '國際特殊教育協會 (International Special Education Association, ISEdA) 成立於 2018 年，是一個以香港為基地、面向全球的非牟利組織。',
    'about.who.p2': '我們相信：<strong>每一個人都值得被看見、被理解、被支持。</strong>無論是 SEN 青年、家長，還是站在第一線的特教從業者，我們都在這裡為您撐起一把傘。',
    'about.who.check1': '以「人」為本，尊重每個人的差異與節奏',
    'about.who.check2': '連結國際資源，接軌全球特教趨勢',
    'about.who.check3': '重視實證研究，所有服務皆有專業根據',
    'about.mv.title': '🎯 使命・願景・核心價值',
    'about.mv.mission.title': '我們的使命',
    'about.mv.mission.desc': '透過教育、培訓與就業支援，賦能 SEN 青年與家庭，讓他們能獨立自主地活出精彩人生。',
    'about.mv.vision.title': '我們的願景',
    'about.mv.vision.desc': '建立一個真正共融的社會——在這裡，差異不是障礙，而是每個人獨特的力量。',
    'about.mv.v1.title': '核心價值一：尊重',
    'about.mv.v1.desc': '尊重每個人的學習節奏、溝通方式與生命經驗，不貼標籤、不設上限。',
    'about.mv.v2.title': '核心價值二：專業',
    'about.mv.v2.desc': '所有服務與建議皆以實證研究為基礎，並持續與國際專家交流進修。',
    'about.mv.v3.title': '核心價值三：陪伴',
    'about.mv.v3.desc': '不只是一次性的協助，而是長期、穩定、有溫度的同行。',
    'about.mv.v4.title': '核心價值四：共融',
    'about.mv.v4.desc': '從校園到職場，我們推動社會各界的理解與接納，讓共融真正發生。',
    'about.timeline.title': '📈 我們的發展歷程',
    'about.timeline.sub': '一步一腳印，走過的每一步都為了讓共融更近一點。',
    'about.timeline.1.title': '協會成立',
    'about.timeline.1.desc': '由一群特教教師、治療師與家長共同創立，舉辦首屆「共融教育講座」。',
    'about.timeline.2.title': '青年就業計劃啟動',
    'about.timeline.2.desc': '推出 SEN 青年職訓與就業配對計劃，首批與 5 間企業建立合作。',
    'about.timeline.3.title': '線上知識庫上線',
    'about.timeline.3.desc': '因應疫情，將培訓課程轉為線上，並開放免費知識庫供公眾查閱。',
    'about.timeline.4.title': '國際認證課程合作',
    'about.timeline.4.desc': '與國際特教機構簽署合作，引進專業證書課程，會員數突破 300 人。',
    'about.timeline.5.title': 'ESG 企業夥伴網絡',
    'about.timeline.5.desc': '正式推出 ESG 合作方案，超過 50 間企業與機構加入共融行列。',
    'about.timeline.6.title': '展望未來',
    'about.timeline.6.desc': '目標：服務超過 1,000 名 SEN 青年，將共融模式推廣至亞太地區。',
    'about.team.title': '👥 核心團隊',
    'about.team.sub': '四位聯合創辦人結合教育、心理、家庭輔導與創意教育專業，攜手同行。',
    'about.team.founder': '聯合創辦人',
    'about.team.details': '專業背景',
    'about.team.1.name': 'ELVIN LAM',
    'about.team.1.role': '註冊心理諮詢師・聯合創辦人',
    'about.team.1.desc': '「療心教育」創辦人、「生命領航協會」總幹事及「看不見的力量」公開演講冠軍。',
    'about.team.1.cred1': '國際款待及服務管理文學士（ENU, UK）',
    'about.team.1.cred2': '註冊心理諮詢師（中國醫學科學院）',
    'about.team.1.cred3': '2025 年成功挑戰戈壁徒步行走 131 公里；2022 年獲人生首項健力士世界紀錄',
    'about.team.2.name': 'HELEN MOK',
    'about.team.2.role': '兒童心理輔導及家庭教育顧問・聯合創辦人',
    'about.team.2.desc': '「Miss Helen 流動教室」創辦人，並擔任家庭輔導、兒童心理與 SEN 生涯規劃相關工作。',
    'about.team.2.cred1': '香港中文大學家庭輔導及家庭教育碩士',
    'about.team.2.cred2': '香港浸會大學心理學一級榮譽學士',
    'about.team.2.cred3': '「愛孩子慈善基金」家庭輔導及教育總監；「OKO Healing」兒童心理諮詢師；「生命領航協會」SEN 生涯規劃顧問',
    'about.team.3.name': 'CHECHE CHENG',
    'about.team.3.role': 'SEN STEM 創意教育總監・聯合創辦人',
    'about.team.3.desc': '「樹鳥計劃」創辦人、「車兒教育」創辦人及營運總監，並統籌教育部活動。',
    'about.team.3.cred1': '教育碩士、PGDE of Early Childhood 及中文系文學士（HKBU）',
    'about.team.3.cred2': '特殊教育輔導證書（香港樹仁大學進修學院）；國家語委普通話水平測試（香港教育大學）',
    'about.team.3.cred3': 'ABRSM 五級樂理、龍鳳字畫導師及泰拳三段位教學導師',
    'about.team.4.name': 'KIMBERLY CHAK',
    'about.team.4.role': '註冊心理諮詢師・聯合創辦人',
    'about.team.4.desc': '「漫事生命培育」及「毛療萬事屋」創辦人，並擔任藝術課程與共融服務顧問。',
    'about.team.4.cred1': '註冊催眠治療師及高級心理諮詢師',
    'about.team.4.cred2': '香港浸會大學視覺藝術文學士',
    'about.team.4.cred3': '曾任香港幼兒教育及服務聯會項目主任及東華三院綜合服務中心工場及宿舍藝術發展主任',
    'about.cta.title': '🤗 想認識我們更多？',
    'about.cta.desc': '歡迎參加我們的公開活動，或直接成為會員，加入這個溫暖的大家庭。',
    'about.cta.btn1': '立即加入會員 💡',
    'about.cta.btn2': '看看近期活動 🗓️',

    // 活動專區
    'events.hero.title': '🗓️ 活動專區',
    'events.hero.sub': '從青年聯誼、家長座談到專業培訓，一起參與、一起成長。',
    'events.title': '📅 敬請期待',
    'events.sub': '我們正在籌備更多精彩活動，敬請期待。',
    'events.empty.title': '敬請期待',
    'events.filter.all': '全部',
    'events.filter.youth': '🙋‍♂️ 青年活動',
    'events.filter.pro': '🧑‍🏫 專業培訓',
    'events.filter.parents': '👨‍👩‍👦 家長支援',
    'events.filter.online': '💻 線上活動',
    'events.btn': '立即登記 (RSVP) ✍️',
    'events.btn2': '加入候補名單 ⏱️',
    'events.empty.desc': '最新活動資訊將於此公布，歡迎稍後再回來查看。',
    'events.tips.title': '💡 參加活動小貼士',
    'events.tips.1.title': '會員優先報名',
    'events.tips.1.desc': '會員可提早 3 天優先報名熱門活動，避免向隅。',
    'events.tips.2.title': '無障礙參與',
    'events.tips.2.desc': '所有實體活動場地皆設有無障礙設施，歡迎提出特殊需要。',
    'events.tips.3.title': '取消政策',
    'events.tips.3.desc': '如需取消，請最遲於活動前 3 天通知，名額將轉讓給候補人士。',
    'events.tips.4.title': '想舉辦活動？',
    'events.tips.4.desc': '機構或學校想與我們合辦活動，歡迎到合作洽談頁聯絡我們。',
    'events.tips.more': '合辦活動・合作洽談 →',

    // 知識庫
    'knowledge.hero.title': '📖 專業特教知識庫',
    'knowledge.hero.sub': '由特教專家撰寫的實用文章，讓知識成為支持的力量。',
    'knowledge.featured.title': '⭐ 本週精選',
    'knowledge.featured.tag': '精選・家長指南',
    'knowledge.featured.h3': '開學焦慮怎麼辦？給 SEN 家長的 5 個實用錦囊',
    'knowledge.featured.desc': '新學期對 SEN 孩子來說，往往是巨大挑戰：新環境、新老師、新規則。本文由臨床心理學家撰寫，從「提前預告、視覺輔助、情緒詞彙、逐步減敏、穩定作息」五個方向，一步步帶您幫孩子安心迎接開學。',
    'knowledge.featured.time': '📝 閱讀時間：10分鐘・更新於 2026年7月',
    'knowledge.featured.btn': '閱讀全文 →',
    'knowledge.all.title': '📚 所有文章',
    'blog.4.tag': '政策新知',
    'blog.4.title': '香港 SEN 支援政策 2026：家長必知的 4 大新措施',
    'blog.4.time': '📝 閱讀時間：7分鐘',
    'blog.5.tag': '工具資源',
    'blog.5.title': '視覺化日程表免費資源：下載即用的 10 款範本',
    'blog.5.time': '📝 閱讀時間：3分鐘',
    'blog.6.tag': '專業培訓',
    'blog.6.title': '課堂上的正向行為支援：第一線教師實戰手冊',
    'blog.6.time': '📝 閱讀時間：12分鐘',
    'blog.7.tag': '青年成長',
    'blog.7.title': '從學校到職場：SEN 青年的生涯規劃地圖',
    'blog.7.time': '📝 閱讀時間：9分鐘',
    'blog.8.tag': '家長指南',
    'blog.8.title': '手足相處：如何照顧 SEN 孩子與兄弟姊妹的需求',
    'blog.8.time': '📝 閱讀時間：6分鐘',
    'blog.9.tag': '工具資源',
    'blog.9.title': '自我倡導 (Self-Advocacy) 訓練：讓青年為自己發聲',
    'blog.9.time': '📝 閱讀時間：8分鐘',
    'knowledge.cta.title': '✍️ 您是特教專家嗎？',
    'knowledge.cta.desc': '我們歡迎從業者、學者與家長投稿分享經驗，讓好知識被更多人看見。',
    'knowledge.cta.btn': '聯絡我們投稿 ↗',

    // 會員專區
    'members.hero.title': '🔘 會員專區',
    'members.hero.sub': '選擇最適合您的會員方案，加入這個互相支持的大家庭。',
    'members.plans.title': '💎 會員方案',
    'members.plans.sub': '無論您是個人還是機構，總有一個方案適合您。',
    'members.plan.free.name': '🙋 免費會員',
    'members.plan.free.per': '/ 永久',
    'members.plan.free.i1': '訂閱電子報與最新活動通知',
    'members.plan.free.i2': '瀏覽知識庫公開文章',
    'members.plan.free.i3': '報名公開活動與講座',
    'members.plan.free.i4': '加入網上共融社群',
    'members.plan.free.btn': '立即免費註冊',
    'members.plan.pro.badge': '最受歡迎 🔥',
    'members.plan.pro.name': '🧑‍🏫 專業會員',
    'members.plan.pro.per': '/ 年',
    'members.plan.pro.i1': '包含免費會員全部權益',
    'members.plan.pro.i2': '活動優先 3 天報名',
    'members.plan.pro.i3': '知識庫會員限定深度文章',
    'members.plan.pro.i4': '專業培訓課程 8 折優惠',
    'members.plan.pro.i5': '國際證書課程資訊與諮詢',
    'members.plan.pro.i6': '參與專業交流小組',
    'members.plan.pro.btn': '加入專業會員',
    'members.plan.org.name': '🏢 機構會員',
    'members.plan.org.per': '/ 年',
    'members.plan.org.i1': '包含專業會員全部權益',
    'members.plan.org.i2': '最多 10 位員工帳號',
    'members.plan.org.i3': '機構專屬培訓方案設計',
    'members.plan.org.i4': '合辦活動與講座機會',
    'members.plan.org.i5': 'ESG 共融職場認證評估',
    'members.plan.org.i6': '媒體曝光與表揚機會',
    'members.plan.org.btn': '洽詢機構方案',
    'members.benefits.title': '🎁 成為會員，您可以獲得',
    'members.benefits.1.title': '活動優先報名',
    'members.benefits.1.desc': '熱門工作坊與講座，會員可提早報名，不怕搶不到名額。',
    'members.benefits.2.title': '深度知識庫',
    'members.benefits.2.desc': '解鎖會員限定文章：個案研究、評估工具與實戰手冊。',
    'members.benefits.3.title': '培訓折扣',
    'members.benefits.3.desc': '專業培訓與國際證書課程，會員享 8 折優惠。',
    'members.benefits.4.title': '專業社群',
    'members.benefits.4.desc': '加入同行交流群組，跨領域請益、資源共享、互相打氣。',
    'members.benefits.5.title': '就業配對',
    'members.benefits.5.desc': 'SEN 青年會員可參與職訓、實習與就業配對計劃。',
    'members.benefits.6.title': '專業諮詢',
    'members.benefits.6.desc': '家長會員每年可享 2 次免費專業諮詢（心理／教育）。',
    'members.form.title': '📝 立即加入我們',
    'members.form.sub': '填寫以下資料，我們會在 3 個工作天內以電郵聯絡您完成註冊。',
    'members.form.name.label': '姓名 *',
    'members.form.name.ph': '您的姓名',
    'members.form.email.label': '電郵 *',
    'members.form.email.ph': '您的電子郵件',
    'members.form.type.label': '會員類別 *',
    'members.form.role.label': '您的身份',
    'members.form.msg.label': '想對我們說的話（選填）',
    'members.form.msg.ph': '例如：想了解什麼服務、有什麼期待...',
    'members.form.submit': '送出申請 🚀',
    'members.form.note': '送出即表示同意我們的會員條款與私隱政策。',
    'members.form.success': '✅ 申請已送出！我們會盡快以電郵聯絡您。',
    'select.default': '請選擇...',
    'select.free': '免費會員',
    'select.pro': '專業會員 (HK$300/年)',
    'select.org': '機構會員 (HK$2,000/年)',
    'select.youth': 'SEN 青年',
    'select.parent': '家長／照顧者',
    'select.teacher': '特教從業者',
    'select.partner': '機構代表',
    'members.faq.title': '❓ 常見問題',
    'members.faq.1.q': '會員資格有年齡限制嗎？',
    'members.faq.1.a': '沒有。我們歡迎任何支持共融理念的人加入。SEN 青年會員建議由 16 歲或以上本人申請；未滿 16 歲可由家長或監護人代為申請。',
    'members.faq.2.q': '專業會員的年費如何繳交？',
    'members.faq.2.a': '我們接受轉數快 (FPS)、銀行轉帳、信用卡及 PayPal 付款。完成註冊申請後，我們會寄送付款連結給您。',
    'members.faq.3.q': '免費會員和專業會員有什麼分別？',
    'members.faq.3.a': '免費會員可訂閱資訊、報名公開活動及瀏覽公開文章；專業會員額外享有活動優先報名、會員限定深度文章、培訓 8 折及專業交流小組等權益。',
    'members.faq.4.q': '我可以升級或降級會員方案嗎？',
    'members.faq.4.a': '可以。您隨時可以透過會員後台升級方案（按比例補差價），或於續期時降級。如有需要，歡迎電郵聯絡我們。',
    'members.faq.5.q': '機構會員可以有多少個帳號？',
    'members.faq.5.a': '機構會員最多可有 10 個員工帳號；如需更多帳號，可另購附加帳號（每個 HK$150/年）。',

    // 合作洽談
    'partners.hero.title': '🏢 合作洽談',
    'partners.hero.sub': '攜手企業與機構，一起打造真正共融的社會與職場。',
    'partners.why.title': '🤝 為什麼與我們合作？',
    'partners.why.sub': '共融不是口號，而是可以量化的社會影響力。與 ISEdA 合作，讓您的 ESG 承諾落地生根。',
    'partners.esg.e.title': '🌍 環境 (E)',
    'partners.esg.e.desc': '舉辦綠色共融活動，將環保理念融入特教服務，實踐雙重社會價值。',
    'partners.esg.s.title': '⚖️ 社會 (S)',
    'partners.esg.s.desc': '提供 SEN 青年實習與就業機會，直接回應多元共融 (D&I) 社會指標。',
    'partners.esg.g.title': '📊 治理 (G)',
    'partners.esg.g.desc': '透明的合作機制與影響力報告，讓每一分支持都有據可查、有數可說。',
    'partners.esg.brand.title': '📣 品牌形象',
    'partners.esg.brand.desc': '透過媒體報導、表揚活動與共融標章，提升企業社會形象與好感度。',
    'partners.modes.title': '💡 合作模式',
    'partners.modes.sub': '無論是資金、人力還是職位，每一種支持都能改變一個青年的人生。',
    'partners.mode.1.title': '💰 贊助支持',
    'partners.mode.1.desc': '贊助活動經費、獎學金或器材，成為我們的長期夥伴。',
    'partners.mode.2.title': '🧑‍🤝‍🧑 企業義工',
    'partners.mode.2.desc': '組織員工參與義工服務，例如職場影子計劃、模擬面試。',
    'partners.mode.3.title': '💼 職位配對',
    'partners.mode.3.desc': '提供實習或正職空缺，由我們協助配對與職場適應支援。',
    'partners.mode.4.title': '🏫 場地與資源',
    'partners.mode.4.desc': '提供場地、課程資源或專業講師，共同舉辦培訓與講座。',
    'partners.wall.title': '🏆 我們的合作夥伴',
    'partners.wall.sub': '感謝以下機構與企業與我們同行。',
    'partners.wall.logo': '[機構標誌]',
    'partners.contact.title': '📩 與我們洽談合作',
    'partners.contact.sub': '透過 WhatsApp 與我們直接聯繫，開始討論合作方向。',
    'partners.whatsapp.heading': '立即透過 WhatsApp 聯繫我們',
    'partners.whatsapp.desc': '歡迎透過 WhatsApp 與我們討論合作構想、資源配對或其他查詢；我們會盡快回覆您。',
    'partners.whatsapp.cta': '在 WhatsApp 聯繫我們 ↗',
    'partners.whatsapp.aria': '透過 WhatsApp 與 ISEdA 聯繫，於新視窗開啟',
    'partners.whatsapp.note': '點擊後將開啟 WhatsApp；您可在對話中自由提供需要的資料。',
    'partners.form.org.label': '機構／公司名稱 *',
    'partners.form.org.ph': '您的機構名稱',
    'partners.form.name.label': '聯絡人姓名 *',
    'partners.form.name.ph': '您的姓名',
    'partners.form.email.label': '聯絡電郵 *',
    'partners.form.email.ph': '您的電子郵件',
    'partners.form.phone.label': '聯絡電話',
    'partners.form.mode.label': '感興趣的合作模式 *',
    'partners.form.msg.label': '合作構想 *',
    'partners.form.msg.ph': '簡單描述您的合作構想、時間與預算範圍...',
    'partners.form.submit': '送出合作提案 📨',
    'partners.form.note': '您的資料只會用於本次合作洽談，絕不對外分享。',
    'partners.form.success': '✅ 提案已送出！我們會盡快與您聯絡。',
    'select.sponsor': '贊助支持',
    'select.volunteer': '企業義工',
    'select.jobs': '職位配對',
    'select.venue': '場地與資源',
    'select.other': '其他／想了解更多'
  },

  /* ============ 簡體中文 ============ */
  'zh-Hans': {
    'brand.zh': '国际特殊教育协会',
    'brand.sub': 'International Special Education Association',
    'nav.home': '首页',
    'nav.about': '关于我们',
    'nav.events': '活动专区',
    'nav.knowledge': '专业知识库',
    'nav.members': '会员专区',
    'nav.partners': '合作洽谈',
    'nav.login': '加入我们',
    'title.join': '加入我们 - ISEdA 国际特殊教育协会',
    'join.hero.title': '加入我们',
    'join.hero.sub': '填写会员登记表单，加入国际特殊教育协会的共融社群。',
    'join.breadcrumb': '加入我们',
    'join.form.title': '会员登记表单',
    'join.form.sub': '请在下方填写表单；您的资料会透过 Google Forms 安全提交。',
    'join.form.unavailable': '您的浏览器无法显示内嵌表单。',
    'join.form.open': '无法使用内嵌表单？在新窗口打开会员登记表单',
    'crumb.home': '首页',
    'crumb.about': '关于我们',
    'crumb.events': '活动专区',
    'crumb.knowledge': '专业知识库',
    'crumb.members': '会员专区',
    'crumb.partners': '合作洽谈',
    'title.index': 'ISEdA 国际特殊教育协会 - 首页',
    'title.about': '关于我们 - ISEdA 国际特殊教育协会',
    'title.events': '活动专区 - ISEdA 国际特殊教育协会',
    'title.knowledge': '专业知识库 - ISEdA 国际特殊教育协会',
    'title.members': '会员专区 - ISEdA 国际特殊教育协会',
    'title.partners': '合作洽谈 - ISEdA 国际特殊教育协会',

    'footer.newsletter.title': '✉️ 订阅最新消息',
    'footer.newsletter.desc': '填写电邮，即可免费订阅我们的特教文章、活动通知与会员资讯。',
    'footer.newsletter.placeholder': '输入您的电子邮件...',
    'footer.newsletter.btn': '立即订阅 📥',
    'footer.newsletter.success': '✅ 订阅成功！我们会定期寄送最新消息给您。',
    'footer.contact': '联系我们',
    'footer.contact.phone': '📞 电话: +852 xxxx xxxx',
    'footer.contact.address': '📍 地址: 香港九龙某共融社区中心',
    'footer.links': '快速链接',
    'alert.email': '请先输入有效的电子邮件地址 📧',

    'index.hero.title': '🌟 连结希望・共融未来',
    'index.hero.sub': '为特殊教育需要 (SEN) 青年、家庭与从业者打造的国际共融平台。',
    'index.hero.btn1': '立即免费加入会员 💡',
    'index.hero.btn2': '探索我们的服务 ↗',
    'index.stats.1': 'SEN 青年受惠',
    'index.stats.2': '特教从业者会员',
    'index.stats.3': '合作机构',
    'index.stats.4': '活动与培训场次',
    'index.about.title': '关于国际特殊教育协会',
    'index.about.p1': 'ISEdA 是一个以香港为基地的国际性非牟利组织，致力于成为连结特殊教育需要 (SEN) 青年、家庭、特教从业者与社会各界的桥梁。',
    'index.about.check1': '提供 SEN 青年升学、职训与就业一条龙支援',
    'index.about.check2': '推动特教从业者专业培训与国际认证',
    'index.about.check3': '陪伴家长与照顾者，推广共融教育理念',
    'index.about.check4': '携手企业落实 ESG，打造共融友善职场',
    'index.about.btn': '了解更多 →',
    'index.portals.title': '我们的服务对象',
    'index.portals.sub': '无论您是青年、从业者、家长，或是想一同推动共融的机构，我们都有专属的服务与资源。',
    'index.portals.youth.title': '🙋‍♂️ SEN 青年',
    'index.portals.youth.desc': '提供升学规划、职业培训、实习机会、就业配对、职场适应支援及领袖培育。',
    'index.portals.youth.link': '寻求支援 →',
    'index.portals.teacher.title': '🧑‍🏫 特教从业者',
    'index.portals.teacher.desc': '提供专业培训、国际证书课程资讯、学术资源共享与专业交流平台。',
    'index.portals.teacher.link': '专业培训 →',
    'index.portals.parents.title': '👨‍👩‍👦 家长与照顾者',
    'index.portals.parents.desc': '提供家长支援小组、专业咨询服务以及共融教育理念推广，与您并肩同行。',
    'index.portals.parents.link': '获取协助 →',
    'index.portals.partners.title': '🏢 合作机构',
    'index.portals.partners.desc': '携手推行 ESG 指标、提高企业社会形象与影响力，共创共融友善职场。',
    'index.portals.partners.link': '合作洽谈 →',
    'index.events.title': '🗓️ 即将举办的精彩活动',
    'index.events.sub': '从青年联谊到专业进修，总有一场活动适合您。立即报名，与我们一起成长！',
    'poster': '[活动海报预留区]',
    'index.blog.title': '📖 专业特教知识与资源',
    'index.blog.sub': '由特教专家与实务工作者撰写的知识库，涵盖家长指南、专业培训与青年成长等主题。',
    'blog.1.tag': '家长指南',
    'blog.1.title': '如何协助 SEN 孩子适应新学期的情绪变化？',
    'blog.1.time': '📝 阅读时间：5分钟',
    'blog.2.tag': '专业培训',
    'blog.2.title': '2026 最新特教证书申请流程与重点解析',
    'blog.2.time': '📝 阅读时间：8分钟',
    'blog.3.tag': '青年成长',
    'blog.3.title': '职场适应的 3 个关键沟通技巧与实战分享',
    'blog.3.time': '📝 阅读时间：6分钟',
    'index.blog.more': '进入专业知识库 →',
    'index.testi.title': '💬 会员与伙伴的真实心声',
    'index.testi.sub': '每一位会员的故事，都是我们持续前进的动力。',
    'index.testi.1.quote': '「透过 ISEdA 的就业配对计划，我找到了一份真正适合自己的工作，同事们也很愿意包容我的步伐。」',
    'index.testi.1.name': '阿杰',
    'index.testi.1.role': 'SEN 青年会员・已成功就业',
    'index.testi.2.quote': '「这里的家长支援小组让我觉得不再孤单。孩子上学的情绪问题，终于有人可以一起商量。」',
    'index.testi.2.name': '陈太太',
    'index.testi.2.role': '家长会员・自闭症孩子妈妈',
    'index.testi.3.quote': '「国际证书课程的内容非常扎实，实务案例分享直接带回教室就能用，对我的教学帮助很大。」',
    'index.testi.3.name': '林老师',
    'index.testi.3.role': '特教从业者・特殊学校教师',
    'index.cta.title': '✨ 准备好加入我们了吗？',
    'index.cta.desc': '免费成为会员，立即获得活动优先报名、知识库资源与最新消息。',
    'index.cta.btn': '立即免费加入 💡',

    'about.hero.title': '🏫 关于我们',
    'about.hero.sub': '了解 ISEdA 的使命、愿景与发展历程。',
    'about.who.title': '我们是谁？',
    'about.who.p1': '国际特殊教育协会 (International Special Education Association, ISEdA) 成立于 2018 年，是一个以香港为基地、面向全球的非牟利组织。',
    'about.who.p2': '我们相信：<strong>每一个人都值得被看见、被理解、被支持。</strong>无论是 SEN 青年、家长，还是站在第一线的特教从业者，我们都在这里为您撑起一把伞。',
    'about.who.check1': '以「人」为本，尊重每个人的差异与节奏',
    'about.who.check2': '连结国际资源，接轨全球特教趋势',
    'about.who.check3': '重视实证研究，所有服务皆有专业根据',
    'about.mv.title': '🎯 使命・愿景・核心价值观',
    'about.mv.mission.title': '我们的使命',
    'about.mv.mission.desc': '透过教育、培训与就业支援，赋能 SEN 青年与家庭，让他们能独立自主地活出精彩人生。',
    'about.mv.vision.title': '我们的愿景',
    'about.mv.vision.desc': '建立一个真正共融的社会——在这里，差异不是障碍，而是每个人独特的力量。',
    'about.mv.v1.title': '核心价值观一：尊重',
    'about.mv.v1.desc': '尊重每个人的学习节奏、沟通方式与生命经验，不贴标签、不设上限。',
    'about.mv.v2.title': '核心价值观二：专业',
    'about.mv.v2.desc': '所有服务与建议皆以实证研究为基础，并持续与国际专家交流进修。',
    'about.mv.v3.title': '核心价值观三：陪伴',
    'about.mv.v3.desc': '不只是一次性的协助，而是长期、稳定、有温度的同行。',
    'about.mv.v4.title': '核心价值观四：共融',
    'about.mv.v4.desc': '从校园到职场，我们推动社会各界的理解与接纳，让共融真正发生。',
    'about.timeline.title': '📈 我们的发展历程',
    'about.timeline.sub': '一步一脚印，走过的每一步都为了让共融更近一点。',
    'about.timeline.1.title': '协会成立',
    'about.timeline.1.desc': '由一群特教教师、治疗师与家长共同创立，举办首届「共融教育讲座」。',
    'about.timeline.2.title': '青年就业计划启动',
    'about.timeline.2.desc': '推出 SEN 青年职训与就业配对计划，首批与 5 间企业建立合作。',
    'about.timeline.3.title': '线上知识库上线',
    'about.timeline.3.desc': '因应疫情，将培训课程转为线上，并开放免费知识库供公众查阅。',
    'about.timeline.4.title': '国际认证课程合作',
    'about.timeline.4.desc': '与国际特教机构签署合作，引进专业证书课程，会员数突破 300 人。',
    'about.timeline.5.title': 'ESG 企业伙伴网络',
    'about.timeline.5.desc': '正式推出 ESG 合作方案，超过 50 间企业与机构加入共融行列。',
    'about.timeline.6.title': '展望未来',
    'about.timeline.6.desc': '目标：服务超过 1,000 名 SEN 青年，将共融模式推广至亚太地区。',
    'about.team.title': '👥 核心团队',
    'about.team.sub': '四位联合创办人结合教育、心理、家庭辅导与创意教育专业，携手同行。',
    'about.team.founder': '联合创办人',
    'about.team.details': '专业背景',
    'about.team.1.name': 'ELVIN LAM',
    'about.team.1.role': '注册心理咨询师・联合创办人',
    'about.team.1.desc': '「疗心教育」创办人、「生命领航协会」总干事及「看不见的力量」公开演讲冠军。',
    'about.team.1.cred1': '国际款待及服务管理文学士（ENU, UK）',
    'about.team.1.cred2': '注册心理咨询师（中国医学科学院）',
    'about.team.1.cred3': '2025 年成功挑战戈壁徒步行走 131 公里；2022 年获人生首项健力士世界纪录',
    'about.team.2.name': 'HELEN MOK',
    'about.team.2.role': '儿童心理辅导及家庭教育顾问・联合创办人',
    'about.team.2.desc': '「Miss Helen 流动教室」创办人，并从事家庭辅导、儿童心理及 SEN 生涯规划相关工作。',
    'about.team.2.cred1': '香港中文大学家庭辅导及家庭教育硕士',
    'about.team.2.cred2': '香港浸会大学心理学一级荣誉学士',
    'about.team.2.cred3': '「爱孩子慈善基金」家庭辅导及教育总监；「OKO Healing」儿童心理咨询师；「生命领航协会」SEN 生涯规划顾问',
    'about.team.3.name': 'CHECHE CHENG',
    'about.team.3.role': 'SEN STEM 创意教育总监・联合创办人',
    'about.team.3.desc': '「树鸟计划」创办人、「车儿教育」创办人及营运总监，并统筹教育部活动。',
    'about.team.3.cred1': '教育硕士、幼儿教育学位教师教育文凭及中文系文学士（HKBU）',
    'about.team.3.cred2': '特殊教育辅导证书（香港树仁大学进修学院）；国家语委普通话水平测试（香港教育大学）',
    'about.team.3.cred3': 'ABRSM 五级乐理、龙凤字画导师及泰拳三段位教学导师',
    'about.team.4.name': 'KIMBERLY CHAK',
    'about.team.4.role': '注册心理咨询师・联合创办人',
    'about.team.4.desc': '「漫事生命培育」及「毛疗万事屋」创办人，并担任艺术课程与共融服务顾问。',
    'about.team.4.cred1': '注册催眠治疗师及高级心理咨询师',
    'about.team.4.cred2': '香港浸会大学视觉艺术文学士',
    'about.team.4.cred3': '曾任香港幼儿教育及服务联会项目主任及东华三院综合服务中心工场及宿舍艺术发展主任',
    'about.cta.title': '🤗 想认识我们更多？',
    'about.cta.desc': '欢迎参加我们的公开活动，或直接成为会员，加入这个温暖的大家庭。',
    'about.cta.btn1': '立即加入会员 💡',
    'about.cta.btn2': '看看近期活动 🗓️',

    'events.hero.title': '🗓️ 活动专区',
    'events.hero.sub': '从青年联谊、家长座谈到专业培训，一起参与、一起成长。',
    'events.title': '📅 敬请期待',
    'events.sub': '我们正在筹备更多精彩活动，敬请期待。',
    'events.empty.title': '敬请期待',
    'events.filter.all': '全部',
    'events.filter.youth': '🙋‍♂️ 青年活动',
    'events.filter.pro': '🧑‍🏫 专业培训',
    'events.filter.parents': '👨‍👩‍👦 家长支援',
    'events.filter.online': '💻 线上活动',
    'events.btn': '立即登记 (RSVP) ✍️',
    'events.btn2': '加入候补名单 ⏱️',
    'events.empty.desc': '最新活动资讯将于此公布，欢迎稍后再回来查看。',
    'events.tips.title': '💡 参加活动小贴士',
    'events.tips.1.title': '会员优先报名',
    'events.tips.1.desc': '会员可提早 3 天优先报名热门活动，避免向隅。',
    'events.tips.2.title': '无障碍参与',
    'events.tips.2.desc': '所有实体活动场地皆设有无障碍设施，欢迎提出特殊需要。',
    'events.tips.3.title': '取消政策',
    'events.tips.3.desc': '如需取消，请最迟于活动前 3 天通知，名额将转让给候补人士。',
    'events.tips.4.title': '想举办活动？',
    'events.tips.4.desc': '机构或学校想与我们合办活动，欢迎到合作洽谈页联系我们。',
    'events.tips.more': '合办活动・合作洽谈 →',

    'knowledge.hero.title': '📖 专业特教知识库',
    'knowledge.hero.sub': '由特教专家撰写的实用文章，让知识成为支持的力量。',
    'knowledge.featured.title': '⭐ 本周精选',
    'knowledge.featured.tag': '精选・家长指南',
    'knowledge.featured.h3': '开学焦虑怎么办？给 SEN 家长的 5 个实用锦囊',
    'knowledge.featured.desc': '新学期对 SEN 孩子来说，往往是巨大挑战：新环境、新老师、新规则。本文由临床心理学家撰写，从「提前预告、视觉辅助、情绪词汇、逐步减敏、稳定作息」五个方向，一步步带您帮孩子安心迎接开学。',
    'knowledge.featured.time': '📝 阅读时间：10分钟・更新于 2026年7月',
    'knowledge.featured.btn': '阅读全文 →',
    'knowledge.all.title': '📚 所有文章',
    'blog.4.tag': '政策新知',
    'blog.4.title': '香港 SEN 支援政策 2026：家长必知的 4 大新措施',
    'blog.4.time': '📝 阅读时间：7分钟',
    'blog.5.tag': '工具资源',
    'blog.5.title': '视觉化日程表免费资源：下载即用的 10 款范本',
    'blog.5.time': '📝 阅读时间：3分钟',
    'blog.6.tag': '专业培训',
    'blog.6.title': '课堂上的正向行为支援：第一线教师实战手册',
    'blog.6.time': '📝 阅读时间：12分钟',
    'blog.7.tag': '青年成长',
    'blog.7.title': '从学校到职场：SEN 青年的生涯规划地图',
    'blog.7.time': '📝 阅读时间：9分钟',
    'blog.8.tag': '家长指南',
    'blog.8.title': '手足相处：如何照顾 SEN 孩子与兄弟姊妹的需求',
    'blog.8.time': '📝 阅读时间：6分钟',
    'blog.9.tag': '工具资源',
    'blog.9.title': '自我倡导 (Self-Advocacy) 训练：让青年为自己发声',
    'blog.9.time': '📝 阅读时间：8分钟',
    'knowledge.cta.title': '✍️ 您是特教专家吗？',
    'knowledge.cta.desc': '我们欢迎从业者、学者与家长投稿分享经验，让好知识被更多人看见。',
    'knowledge.cta.btn': '联系我们投稿 ↗',

    'members.hero.title': '🔘 会员专区',
    'members.hero.sub': '选择最适合您的会员方案，加入这个互相支持的大家庭。',
    'members.plans.title': '💎 会员方案',
    'members.plans.sub': '无论您是个人还是机构，总有一个方案适合您。',
    'members.plan.free.name': '🙋 免费会员',
    'members.plan.free.per': '/ 永久',
    'members.plan.free.i1': '订阅电子报与最新活动通知',
    'members.plan.free.i2': '浏览知识库公开文章',
    'members.plan.free.i3': '报名公开活动与讲座',
    'members.plan.free.i4': '加入网上共融社群',
    'members.plan.free.btn': '立即免费注册',
    'members.plan.pro.badge': '最受欢迎 🔥',
    'members.plan.pro.name': '🧑‍🏫 专业会员',
    'members.plan.pro.per': '/ 年',
    'members.plan.pro.i1': '包含免费会员全部权益',
    'members.plan.pro.i2': '活动优先 3 天报名',
    'members.plan.pro.i3': '知识库会员限定深度文章',
    'members.plan.pro.i4': '专业培训课程 8 折优惠',
    'members.plan.pro.i5': '国际证书课程资讯与咨询',
    'members.plan.pro.i6': '参与专业交流小组',
    'members.plan.pro.btn': '加入专业会员',
    'members.plan.org.name': '🏢 机构会员',
    'members.plan.org.per': '/ 年',
    'members.plan.org.i1': '包含专业会员全部权益',
    'members.plan.org.i2': '最多 10 位员工账号',
    'members.plan.org.i3': '机构专属培训方案设计',
    'members.plan.org.i4': '合办活动与讲座机会',
    'members.plan.org.i5': 'ESG 共融职场认证评估',
    'members.plan.org.i6': '媒体曝光与表扬机会',
    'members.plan.org.btn': '洽询机构方案',
    'members.benefits.title': '🎁 成为会员，您可以获得',
    'members.benefits.1.title': '活动优先报名',
    'members.benefits.1.desc': '热门工作坊与讲座，会员可提早报名，不怕抢不到名额。',
    'members.benefits.2.title': '深度知识库',
    'members.benefits.2.desc': '解锁会员限定文章：个案研究、评估工具与实战手册。',
    'members.benefits.3.title': '培训折扣',
    'members.benefits.3.desc': '专业培训与国际证书课程，会员享 8 折优惠。',
    'members.benefits.4.title': '专业社群',
    'members.benefits.4.desc': '加入同行交流群组，跨领域请益、资源共享、互相打气。',
    'members.benefits.5.title': '就业配对',
    'members.benefits.5.desc': 'SEN 青年会员可参与职训、实习与就业配对计划。',
    'members.benefits.6.title': '专业咨询',
    'members.benefits.6.desc': '家长会员每年可享 2 次免费专业咨询（心理／教育）。',
    'members.form.title': '📝 立即加入我们',
    'members.form.sub': '填写以下资料，我们会在 3 个工作天内以电邮联络您完成注册。',
    'members.form.name.label': '姓名 *',
    'members.form.name.ph': '您的姓名',
    'members.form.email.label': '电邮 *',
    'members.form.email.ph': '您的电子邮件',
    'members.form.type.label': '会员类别 *',
    'members.form.role.label': '您的身份',
    'members.form.msg.label': '想对我们说的话（选填）',
    'members.form.msg.ph': '例如：想了解什么服务、有什么期待...',
    'members.form.submit': '送出申请 🚀',
    'members.form.note': '送出即表示同意我们的会员条款与私隐政策。',
    'members.form.success': '✅ 申请已送出！我们会尽快以电邮联络您。',
    'select.default': '请选择...',
    'select.free': '免费会员',
    'select.pro': '专业会员 (HK$300/年)',
    'select.org': '机构会员 (HK$2,000/年)',
    'select.youth': 'SEN 青年',
    'select.parent': '家长／照顾者',
    'select.teacher': '特教从业者',
    'select.partner': '机构代表',
    'members.faq.title': '❓ 常见问题',
    'members.faq.1.q': '会员资格有年龄限制吗？',
    'members.faq.1.a': '没有。我们欢迎任何支持共融理念的人加入。SEN 青年会员建议由 16 岁或以上本人申请；未满 16 岁可由家长或监护人代为申请。',
    'members.faq.2.q': '专业会员的年费如何缴交？',
    'members.faq.2.a': '我们接受转数快 (FPS)、银行转账、信用卡及 PayPal 付款。完成注册申请后，我们会寄送付款连结给您。',
    'members.faq.3.q': '免费会员和专业会员有什么分别？',
    'members.faq.3.a': '免费会员可订阅资讯、报名公开活动及浏览公开文章；专业会员额外享有活动优先报名、会员限定深度文章、培训 8 折及专业交流小组等权益。',
    'members.faq.4.q': '我可以升级或降级会员方案吗？',
    'members.faq.4.a': '可以。您随时可以通过会员后台升级方案（按比例补差价），或于续期时降级。如有需要，欢迎电邮联系我们。',
    'members.faq.5.q': '机构会员可以有多少个账号？',
    'members.faq.5.a': '机构会员最多可有 10 个员工账号；如需更多账号，可另购附加账号（每个 HK$150/年）。',

    'partners.hero.title': '🏢 合作洽谈',
    'partners.hero.sub': '携手企业与机构，一起打造真正共融的社会与职场。',
    'partners.why.title': '🤝 为什么与我们合作？',
    'partners.why.sub': '共融不是口号，而是可以量化的社会影响力。与 ISEdA 合作，让您的 ESG 承诺落地生根。',
    'partners.esg.e.title': '🌍 环境 (E)',
    'partners.esg.e.desc': '举办绿色共融活动，将环保理念融入特教服务，实践双重社会价值。',
    'partners.esg.s.title': '⚖️ 社会 (S)',
    'partners.esg.s.desc': '提供 SEN 青年实习与就业机会，直接回应多元共融 (D&I) 社会指标。',
    'partners.esg.g.title': '📊 治理 (G)',
    'partners.esg.g.desc': '透明的合作机制与影响力报告，让每一分支持都有据可查、有数可说。',
    'partners.esg.brand.title': '📣 品牌形象',
    'partners.esg.brand.desc': '透过媒体报道、表扬活动与共融标章，提升企业社会形象与好感度。',
    'partners.modes.title': '💡 合作模式',
    'partners.modes.sub': '无论是资金、人力还是职位，每一种支持都能改变一个青年的人生。',
    'partners.mode.1.title': '💰 赞助支持',
    'partners.mode.1.desc': '赞助活动经费、奖学金或器材，成为我们的长期伙伴。',
    'partners.mode.2.title': '🧑‍🤝‍🧑 企业义工',
    'partners.mode.2.desc': '组织员工参与义工服务，例如职场影子计划、模拟面试。',
    'partners.mode.3.title': '💼 职位配对',
    'partners.mode.3.desc': '提供实习或正职空缺，由我们协助配对与职场适应支援。',
    'partners.mode.4.title': '🏫 场地与资源',
    'partners.mode.4.desc': '提供场地、课程资源或专业讲师，共同举办培训与讲座。',
    'partners.wall.title': '🏆 我们的合作伙伴',
    'partners.wall.sub': '感谢以下机构与企业与我们同行。',
    'partners.wall.logo': '[机构标志]',
    'partners.contact.title': '📩 与我们洽谈合作',
    'partners.contact.sub': '通过 WhatsApp 与我们直接联系，开始讨论合作方向。',
    'partners.whatsapp.heading': '立即通过 WhatsApp 联系我们',
    'partners.whatsapp.desc': '欢迎通过 WhatsApp 与我们讨论合作构想、资源配对或其他查询；我们会尽快回复您。',
    'partners.whatsapp.cta': '在 WhatsApp 联系我们 ↗',
    'partners.whatsapp.aria': '通过 WhatsApp 与 ISEdA 联系，于新窗口打开',
    'partners.whatsapp.note': '点击后将打开 WhatsApp；您可在对话中自由提供需要的资料。',
    'partners.form.org.label': '机构／公司名称 *',
    'partners.form.org.ph': '您的机构名称',
    'partners.form.name.label': '联系人姓名 *',
    'partners.form.name.ph': '您的姓名',
    'partners.form.email.label': '联络电邮 *',
    'partners.form.email.ph': '您的电子邮件',
    'partners.form.phone.label': '联络电话',
    'partners.form.mode.label': '感兴趣的合作模式 *',
    'partners.form.msg.label': '合作构想 *',
    'partners.form.msg.ph': '简单描述您的合作构想、时间与预算范围...',
    'partners.form.submit': '送出合作提案 📨',
    'partners.form.note': '您的资料只会用于本次合作洽谈，绝不对外分享。',
    'partners.form.success': '✅ 提案已送出！我们会尽快与您联络。',
    'select.sponsor': '赞助支持',
    'select.volunteer': '企业义工',
    'select.jobs': '职位配对',
    'select.venue': '场地与资源',
    'select.other': '其他／想了解更多'
  },

  /* ============ English ============ */
  'en': {
    'brand.zh': 'International Special Education Association',
    'brand.sub': 'ISEdA',
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.events': 'Events',
    'nav.knowledge': 'Knowledge Hub',
    'nav.members': 'Membership',
    'nav.partners': 'Partners',
    'nav.login': 'Join Us',
    'title.join': 'Join Us - ISEdA International Special Education Association',
    'join.hero.title': 'Join Us',
    'join.hero.sub': 'Complete the membership registration form and join ISEdA’s inclusive community.',
    'join.breadcrumb': 'Join Us',
    'join.form.title': 'Membership Registration Form',
    'join.form.sub': 'Please complete the form below. Your information is securely submitted through Google Forms.',
    'join.form.unavailable': 'Your browser cannot display the embedded form.',
    'join.form.open': 'Unable to use the embedded form? Open the membership registration form in a new window',
    'crumb.home': 'Home',
    'crumb.about': 'About Us',
    'crumb.events': 'Events',
    'crumb.knowledge': 'Knowledge Hub',
    'crumb.members': 'Membership',
    'crumb.partners': 'Partners',
    'title.index': 'ISEdA International Special Education Association - Home',
    'title.about': 'About Us - ISEdA International Special Education Association',
    'title.events': 'Events - ISEdA International Special Education Association',
    'title.knowledge': 'Knowledge Hub - ISEdA International Special Education Association',
    'title.members': 'Membership - ISEdA International Special Education Association',
    'title.partners': 'Partners - ISEdA International Special Education Association',

    'footer.newsletter.title': '✉️ Subscribe to Our Newsletter',
    'footer.newsletter.desc': 'Enter your email to get our special education articles, event updates and member news for free.',
    'footer.newsletter.placeholder': 'Enter your email...',
    'footer.newsletter.btn': 'Subscribe 📥',
    'footer.newsletter.success': '✅ Subscribed! We will send you our latest news regularly.',
    'footer.contact': 'Contact Us',
    'footer.contact.phone': '📞 Tel: +852 xxxx xxxx',
    'footer.contact.address': '📍 Address: An Inclusive Community Centre, Kowloon, Hong Kong',
    'footer.links': 'Quick Links',
    'alert.email': 'Please enter a valid email address 📧',

    'index.hero.title': '🌟 Connecting Hope, Building an Inclusive Future',
    'index.hero.sub': 'An international inclusive platform for young people with Special Educational Needs (SEN), their families and practitioners.',
    'index.hero.btn1': 'Join Free Now 💡',
    'index.hero.btn2': 'Explore Our Services ↗',
    'index.stats.1': 'SEN youth supported',
    'index.stats.2': 'practitioner members',
    'index.stats.3': 'partner organisations',
    'index.stats.4': 'events & trainings held',
    'index.about.title': 'About ISEdA',
    'index.about.p1': 'ISEdA is a Hong Kong-based international non-profit organisation serving as a bridge between young people with Special Educational Needs (SEN), families, special education practitioners and the wider community.',
    'index.about.check1': 'One-stop support for SEN youth: study planning, vocational training and employment',
    'index.about.check2': 'Professional training and international certification for practitioners',
    'index.about.check3': 'Companionship for parents and carers, promoting inclusive education',
    'index.about.check4': 'Working with businesses on ESG to build inclusive workplaces',
    'index.about.btn': 'Learn More →',
    'index.portals.title': 'Who We Serve',
    'index.portals.sub': 'Whether you are a young person, a practitioner, a parent, or an organisation championing inclusion, we have dedicated services for you.',
    'index.portals.youth.title': '🙋‍♂️ SEN Youth',
    'index.portals.youth.desc': 'Study planning, vocational training, internships, job matching, workplace adaptation support and leadership development.',
    'index.portals.youth.link': 'Get Support →',
    'index.portals.teacher.title': '🧑‍🏫 Practitioners',
    'index.portals.teacher.desc': 'Professional training, international certification information, academic resources and a peer-exchange platform.',
    'index.portals.teacher.link': 'Training →',
    'index.portals.parents.title': '👨‍👩‍👦 Parents & Carers',
    'index.portals.parents.desc': 'Parent support groups, professional consultation and inclusive-education advocacy — we walk alongside you.',
    'index.portals.parents.link': 'Get Help →',
    'index.portals.partners.title': '🏢 Partner Organisations',
    'index.portals.partners.desc': 'Partner with us on ESG goals, boost your social image and impact, and build inclusive workplaces together.',
    'index.portals.partners.link': 'Partner With Us →',
    'index.events.title': '🗓️ Upcoming Events',
    'index.events.sub': 'From youth meetups to professional development — there is an event for you. Sign up now!',
    'poster': '[Event poster placeholder]',
    'index.blog.title': '📖 Knowledge & Resources',
    'index.blog.sub': 'Articles by special education experts and practitioners on parenting guides, professional training and youth growth.',
    'blog.1.tag': 'Parenting Guide',
    'blog.1.title': 'How to Help Your SEN Child Cope with Back-to-School Emotions?',
    'blog.1.time': '📝 Read time: 5 min',
    'blog.2.tag': 'Training',
    'blog.2.title': '2026 Guide: Applying for Special Education Certifications',
    'blog.2.time': '📝 Read time: 8 min',
    'blog.3.tag': 'Youth Growth',
    'blog.3.title': '3 Key Communication Skills for Workplace Adaptation',
    'blog.3.time': '📝 Read time: 6 min',
    'index.blog.more': 'Visit the Knowledge Hub →',
    'index.testi.title': '💬 Stories from Our Community',
    'index.testi.sub': 'Every member story keeps us moving forward.',
    'index.testi.1.quote': '"Through ISEdA\'s job matching programme, I found a job that truly suits me, and my colleagues are very understanding of my pace."',
    'index.testi.1.name': 'Jay',
    'index.testi.1.role': 'SEN youth member · Now employed',
    'index.testi.2.quote': '"The parent support group here makes me feel less alone. Finally, there are people to talk to about my child\'s school emotions."',
    'index.testi.2.name': 'Mrs. Chan',
    'index.testi.2.role': 'Parent member · Mum of an autistic child',
    'index.testi.3.quote': '"The international certification course is very solid — I can take the case studies straight back to my classroom. It helps my teaching a lot."',
    'index.testi.3.name': 'Ms. Lam',
    'index.testi.3.role': 'Practitioner · Special school teacher',
    'index.cta.title': '✨ Ready to Join Us?',
    'index.cta.desc': 'Become a member for free and get priority event registration, knowledge resources and the latest news.',
    'index.cta.btn': 'Join Free Now 💡',

    'about.hero.title': '🏫 About Us',
    'about.hero.sub': 'Learn about ISEdA\'s mission, vision and journey.',
    'about.who.title': 'Who We Are',
    'about.who.p1': 'Founded in 2018, ISEdA (International Special Education Association) is a Hong Kong-based, globally focused non-profit organisation.',
    'about.who.p2': 'We believe <strong>everyone deserves to be seen, understood and supported.</strong> Whether you are a SEN young person, a parent, or a frontline practitioner, we have got your back.',
    'about.who.check1': 'People-first: we respect each person\'s differences and pace',
    'about.who.check2': 'Connecting international resources and global special education trends',
    'about.who.check3': 'Evidence-based practice behind every service',
    'about.mv.title': '🎯 Mission, Vision & Values',
    'about.mv.mission.title': 'Our Mission',
    'about.mv.mission.desc': 'To empower SEN youth and families through education, training and employment support, so they can live fulfilling, independent lives.',
    'about.mv.vision.title': 'Our Vision',
    'about.mv.vision.desc': 'To build a truly inclusive society where difference is not a barrier but each person\'s unique strength.',
    'about.mv.v1.title': 'Value 1: Respect',
    'about.mv.v1.desc': 'We respect each person\'s learning pace, communication style and life experience — no labels, no limits.',
    'about.mv.v2.title': 'Value 2: Professionalism',
    'about.mv.v2.desc': 'All services and advice are evidence-based, and we keep learning from international experts.',
    'about.mv.v3.title': 'Value 3: Companionship',
    'about.mv.v3.desc': 'Not one-off help, but long-term, steady and warm companionship.',
    'about.mv.v4.title': 'Value 4: Inclusion',
    'about.mv.v4.desc': 'From school to workplace, we promote understanding and acceptance so that inclusion truly happens.',
    'about.timeline.title': '📈 Our Journey',
    'about.timeline.sub': 'Step by step, every milestone brings inclusion closer.',
    'about.timeline.1.title': 'Founding of ISEdA',
    'about.timeline.1.desc': 'Founded by special education teachers, therapists and parents; hosted the first Inclusive Education Seminar.',
    'about.timeline.2.title': 'Youth Employment Programme Launched',
    'about.timeline.2.desc': 'Launched vocational training and job matching for SEN youth, partnering with 5 companies.',
    'about.timeline.3.title': 'Online Knowledge Hub Launched',
    'about.timeline.3.desc': 'Moved training online during the pandemic and opened a free public knowledge hub.',
    'about.timeline.4.title': 'International Certification Partnership',
    'about.timeline.4.desc': 'Signed partnerships with international institutions to bring in professional certification courses; membership exceeded 300.',
    'about.timeline.5.title': 'ESG Corporate Partner Network',
    'about.timeline.5.desc': 'Officially launched ESG partnership programmes; over 50 companies and organisations joined.',
    'about.timeline.6.title': 'Looking Ahead',
    'about.timeline.6.desc': 'Goal: serve 1,000+ SEN youth and bring the inclusion model to the Asia-Pacific region.',
    'about.team.title': '👥 Core Team',
    'about.team.sub': 'Four co-founders bringing together expertise in education, psychology, family guidance and creative education.',
    'about.team.founder': 'CO-FOUNDER',
    'about.team.details': 'Professional Background',
    'about.team.1.name': 'ELVIN LAM',
    'about.team.1.role': 'Registered Senior Psychological Counselor · Co-Founder',
    'about.team.1.desc': 'Founder of OKO Healing Education, Executive Director of Life Leading Association, SEN counselling specialist of Child Cares Foundation and champion public speaker of “The Power of Unseen”.',
    'about.team.1.cred1': 'BA in International Hospitality & Service Management (ENU, UK)',
    'about.team.1.cred2': 'Mental Health First Aid (MHAHK)',
    'about.team.1.cred3': 'Champion public speaker of “The Power of Unseen”',
    'about.team.2.name': 'HELEN MOK',
    'about.team.2.role': 'Child Psychological Counseling & Family Education Consultant · Co-Founder',
    'about.team.2.desc': 'Founder of Miss Helen’s Education and a practitioner in family counseling, child psychology and SEN career planning.',
    'about.team.2.cred1': 'Master of Arts in Family Counseling and Family Education (CUHK)',
    'about.team.2.cred2': 'Bachelor of Social Science (First Class Honors) in Psychology',
    'about.team.2.cred3': 'Family Counseling & Education Director of Child Cares Foundation; Child Psychological Consultant of OKO Healing Education; Family Counseling & Education Director of Life Leading Association',
    'about.team.3.name': 'CHECHE CHENG',
    'about.team.3.role': 'STEM Creative Education Director · Co-Founder',
    'about.team.3.desc': 'Founder of Vermilion Education & Culture Ltd and CheChe Education; Event Coordinator of Hong Kong Students’ Union Parent Association.',
    'about.team.3.cred1': 'Master of Education, PGDE of Early Childhood and BA (Hons) in Chinese Language (HKBU)',
    'about.team.3.cred2': 'Certificate in Special Education Guidance and National Putonghua Proficiency Test (The Education University of Hong Kong)',
    'about.team.3.cred3': 'ABRSM Grade 5 Theory; Dragon-and-Phoenix Calligraphy Instructor; Muay Thai Level 3 Teaching Instructor',
    'about.team.4.name': 'KIMBERLY CHAK',
    'about.team.4.role': 'Registered Senior Psychological Counselor · Co-Founder',
    'about.team.4.desc': 'Founder of Mannaz With-in Life Nurture Limited and Pawer Hub; advisor in arts programmes and inclusive services.',
    'about.team.4.cred1': 'Certified Hypnotherapist and Registered Senior Psychological Counselor',
    'about.team.4.cred2': 'Bachelor of Arts (Hons) in Visual Arts (HKBU)',
    'about.team.4.cred3': 'Former Development Officer at The Hong Kong Council of Early Childhood Education and Services and Art Development Officer at Tung Wah Group of Hospitals Integrated Services Centre Workshop and Hostel',
    'about.cta.title': '🤗 Want to Know More?',
    'about.cta.desc': 'Join our public events, or become a member of this warm community.',
    'about.cta.btn1': 'Join Us Now 💡',
    'about.cta.btn2': 'See Upcoming Events 🗓️',

    'events.hero.title': '🗓️ Events',
    'events.hero.sub': 'From youth meetups and parent talks to professional training — join us and grow together.',
    'events.title': '📅 Coming Soon',
    'events.sub': 'We are preparing more inspiring events. Please stay tuned.',
    'events.empty.title': 'Coming Soon',
    'events.filter.all': 'All',
    'events.filter.youth': '🙋‍♂️ Youth',
    'events.filter.pro': '🧑‍🏫 Training',
    'events.filter.parents': '👨‍👩‍👦 Parents',
    'events.filter.online': '💻 Online',
    'events.btn': 'Register Now (RSVP) ✍️',
    'events.btn2': 'Join Waitlist ⏱️',
    'events.empty.desc': 'New event information will be announced here. Please check back soon.',
    'events.tips.title': '💡 Good to Know',
    'events.tips.1.title': 'Members Register First',
    'events.tips.1.desc': 'Members can register 3 days early for popular events.',
    'events.tips.2.title': 'Accessibility',
    'events.tips.2.desc': 'All venues are accessible — please let us know your needs.',
    'events.tips.3.title': 'Cancellation Policy',
    'events.tips.3.desc': 'To cancel, please notify us at least 3 days before the event so your spot can go to someone on the waitlist.',
    'events.tips.4.title': 'Want to Co-host?',
    'events.tips.4.desc': 'Organisations or schools wishing to co-host events — contact us via the Partners page.',
    'events.tips.more': 'Co-host an Event →',

    'knowledge.hero.title': '📖 Knowledge Hub',
    'knowledge.hero.sub': 'Practical articles by special education experts — knowledge that supports.',
    'knowledge.featured.title': '⭐ Featured This Week',
    'knowledge.featured.tag': 'Featured · Parenting Guide',
    'knowledge.featured.h3': 'Back-to-School Anxiety? 5 Practical Tips for SEN Parents',
    'knowledge.featured.desc': 'A new school year is often a huge challenge for SEN children: new environment, new teachers, new rules. Written by a clinical psychologist, this article walks you through five steps — advance notice, visual aids, emotion vocabulary, gradual desensitisation and a stable routine — to help your child start school with confidence.',
    'knowledge.featured.time': '📝 Read time: 10 min · Updated Jul 2026',
    'knowledge.featured.btn': 'Read Full Article →',
    'knowledge.all.title': '📚 All Articles',
    'blog.4.tag': 'Policy News',
    'blog.4.title': 'Hong Kong SEN Support Policy 2026: 4 New Measures Parents Should Know',
    'blog.4.time': '📝 Read time: 7 min',
    'blog.5.tag': 'Resources',
    'blog.5.title': 'Free Visual Schedule Templates: 10 Ready-to-Use Downloads',
    'blog.5.time': '📝 Read time: 3 min',
    'blog.6.tag': 'Training',
    'blog.6.title': 'Positive Behaviour Support in the Classroom: A Teacher\'s Field Guide',
    'blog.6.time': '📝 Read time: 12 min',
    'blog.7.tag': 'Youth Growth',
    'blog.7.title': 'From School to Work: A Career Planning Map for SEN Youth',
    'blog.7.time': '📝 Read time: 9 min',
    'blog.8.tag': 'Parenting Guide',
    'blog.8.title': 'Siblings: Balancing the Needs of Your SEN Child and Their Brothers and Sisters',
    'blog.8.time': '📝 Read time: 6 min',
    'blog.9.tag': 'Resources',
    'blog.9.title': 'Self-Advocacy Training: Helping Youth Speak Up for Themselves',
    'blog.9.time': '📝 Read time: 8 min',
    'knowledge.cta.title': '✍️ Are You a Special Education Expert?',
    'knowledge.cta.desc': 'Practitioners, academics and parents are welcome to contribute — great knowledge deserves to be seen.',
    'knowledge.cta.btn': 'Contact Us to Contribute ↗',

    'members.hero.title': '🔘 Membership',
    'members.hero.sub': 'Choose the plan that suits you best and join this supportive community.',
    'members.plans.title': '💎 Membership Plans',
    'members.plans.sub': 'Whether you are an individual or an organisation, there is a plan for you.',
    'members.plan.free.name': '🙋 Free Member',
    'members.plan.free.per': '/ lifetime',
    'members.plan.free.i1': 'Newsletter and latest event notifications',
    'members.plan.free.i2': 'Access to public articles in the Knowledge Hub',
    'members.plan.free.i3': 'Register for public events and talks',
    'members.plan.free.i4': 'Join the online inclusion community',
    'members.plan.free.btn': 'Register Free Now',
    'members.plan.pro.badge': 'Most Popular 🔥',
    'members.plan.pro.name': '🧑‍🏫 Professional Member',
    'members.plan.pro.per': '/ yr',
    'members.plan.pro.i1': 'All Free Member benefits',
    'members.plan.pro.i2': '3-day early registration for events',
    'members.plan.pro.i3': 'Member-only in-depth articles',
    'members.plan.pro.i4': '20% off professional training courses',
    'members.plan.pro.i5': 'International certification information and advice',
    'members.plan.pro.i6': 'Join professional discussion groups',
    'members.plan.pro.btn': 'Join as Professional',
    'members.plan.org.name': '🏢 Organisation Member',
    'members.plan.org.per': '/ yr',
    'members.plan.org.i1': 'All Professional Member benefits',
    'members.plan.org.i2': 'Up to 10 staff accounts',
    'members.plan.org.i3': 'Customised training programmes for your organisation',
    'members.plan.org.i4': 'Opportunities to co-host events and talks',
    'members.plan.org.i5': 'ESG inclusive workplace certification review',
    'members.plan.org.i6': 'Media exposure and recognition opportunities',
    'members.plan.org.btn': 'Enquire About Organisations',
    'members.benefits.title': '🎁 Member Benefits',
    'members.benefits.1.title': 'Priority Registration',
    'members.benefits.1.desc': 'Register early for popular workshops and talks — never miss out.',
    'members.benefits.2.title': 'In-Depth Knowledge Hub',
    'members.benefits.2.desc': 'Unlock member-only articles: case studies, assessment tools and field guides.',
    'members.benefits.3.title': 'Training Discounts',
    'members.benefits.3.desc': '20% off professional training and international certification courses.',
    'members.benefits.4.title': 'Professional Community',
    'members.benefits.4.desc': 'Join peer groups for cross-disciplinary advice, resource sharing and encouragement.',
    'members.benefits.5.title': 'Job Matching',
    'members.benefits.5.desc': 'SEN youth members can join vocational training, internships and job matching.',
    'members.benefits.6.title': 'Professional Consultation',
    'members.benefits.6.desc': 'Parent members enjoy 2 free consultations per year (psychology / education).',
    'members.form.title': '📝 Join Us Now',
    'members.form.sub': 'Fill in the form and we will email you within 3 working days to complete your registration.',
    'members.form.name.label': 'Name *',
    'members.form.name.ph': 'Your name',
    'members.form.email.label': 'Email *',
    'members.form.email.ph': 'Your email',
    'members.form.type.label': 'Membership type *',
    'members.form.role.label': 'Your role',
    'members.form.msg.label': 'Message (optional)',
    'members.form.msg.ph': 'e.g. What services are you interested in?',
    'members.form.submit': 'Submit Application 🚀',
    'members.form.note': 'By submitting you agree to our membership terms and privacy policy.',
    'members.form.success': '✅ Application submitted! We will contact you by email soon.',
    'select.default': 'Please select...',
    'select.free': 'Free member',
    'select.pro': 'Professional member (HK$300/yr)',
    'select.org': 'Organisation member (HK$2,000/yr)',
    'select.youth': 'SEN youth',
    'select.parent': 'Parent / carer',
    'select.teacher': 'Practitioner',
    'select.partner': 'Organisation representative',
    'members.faq.title': '❓ FAQ',
    'members.faq.1.q': 'Is there an age limit for membership?',
    'members.faq.1.a': 'No. Anyone who supports inclusion is welcome. SEN youth members aged 16+ can apply on their own; those under 16 can be registered by a parent or guardian.',
    'members.faq.2.q': 'How do I pay the annual fee?',
    'members.faq.2.a': 'We accept FPS, bank transfer, credit card and PayPal. We will send you a payment link after your application.',
    'members.faq.3.q': 'What is the difference between free and professional membership?',
    'members.faq.3.a': 'Free members get newsletters, public events and public articles; professional members additionally get priority registration, member-only articles, 20% off training and professional discussion groups.',
    'members.faq.4.q': 'Can I upgrade or downgrade my plan?',
    'members.faq.4.a': 'Yes. Upgrade anytime via the member portal (pro-rated) or downgrade at renewal. Email us if you need help.',
    'members.faq.5.q': 'How many accounts does an organisation membership include?',
    'members.faq.5.a': 'Up to 10 employee accounts; extra accounts can be added at HK$150/yr each.',

    'partners.hero.title': '🏢 Partners',
    'partners.hero.sub': 'Join forces with us to build a truly inclusive society and workplace.',
    'partners.why.title': '🤝 Why Partner With Us?',
    'partners.why.sub': 'Inclusion is not a slogan — it is measurable social impact. Partner with ISEdA to put your ESG commitments into action.',
    'partners.esg.e.title': '🌍 Environment (E)',
    'partners.esg.e.desc': 'Host green inclusive events, weaving sustainability into special education services for double social impact.',
    'partners.esg.s.title': '⚖️ Social (S)',
    'partners.esg.s.desc': 'Offer internships and jobs to SEN youth, directly addressing diversity & inclusion (D&I) metrics.',
    'partners.esg.g.title': '📊 Governance (G)',
    'partners.esg.g.desc': 'Transparent partnership mechanisms and impact reports — every bit of support is accountable.',
    'partners.esg.brand.title': '📣 Brand Image',
    'partners.esg.brand.desc': 'Raise your corporate image and goodwill through media coverage, recognition events and inclusion badges.',
    'partners.modes.title': '💡 Ways to Partner',
    'partners.modes.sub': 'Funding, people or jobs — every kind of support can change a young person\'s life.',
    'partners.mode.1.title': '💰 Sponsorship',
    'partners.mode.1.desc': 'Sponsor events, scholarships or equipment and become a long-term partner.',
    'partners.mode.2.title': '🧑‍🤝‍🧑 Corporate Volunteering',
    'partners.mode.2.desc': 'Engage your staff in volunteering such as job-shadowing and mock interviews.',
    'partners.mode.3.title': '💼 Job Matching',
    'partners.mode.3.desc': 'Offer internships or jobs; we handle matching and workplace adaptation support.',
    'partners.mode.4.title': '🏫 Venues & Resources',
    'partners.mode.4.desc': 'Provide venues, course resources or expert speakers to co-host training and talks.',
    'partners.wall.title': '🏆 Our Partners',
    'partners.wall.sub': 'Thank you to the organisations and companies walking with us.',
    'partners.wall.logo': '[Logo]',
    'partners.contact.title': '📩 Get in Touch',
    'partners.contact.sub': 'Message us directly on WhatsApp to start the conversation about working together.',
    'partners.whatsapp.heading': 'Connect with us on WhatsApp',
    'partners.whatsapp.desc': 'Message us on WhatsApp about partnership ideas, resource matching or other enquiries. We will get back to you as soon as we can.',
    'partners.whatsapp.cta': 'Contact us on WhatsApp ↗',
    'partners.whatsapp.aria': 'Contact ISEdA on WhatsApp, opens in a new window',
    'partners.whatsapp.note': 'Selecting this button opens WhatsApp, where you can choose what information to share.',
    'partners.form.org.label': 'Organisation / company *',
    'partners.form.org.ph': 'Your organisation',
    'partners.form.name.label': 'Contact name *',
    'partners.form.name.ph': 'Your name',
    'partners.form.email.label': 'Contact email *',
    'partners.form.email.ph': 'Your email',
    'partners.form.phone.label': 'Phone',
    'partners.form.mode.label': 'Partnership type *',
    'partners.form.msg.label': 'Your proposal *',
    'partners.form.msg.ph': 'Briefly describe your idea, timeline and budget...',
    'partners.form.submit': 'Send Proposal 📨',
    'partners.form.note': 'Your information is used only for this enquiry and never shared.',
    'partners.form.success': '✅ Proposal sent! We will be in touch soon.',
    'select.sponsor': 'Sponsorship',
    'select.volunteer': 'Corporate volunteering',
    'select.jobs': 'Job matching',
    'select.venue': 'Venues & resources',
    'select.other': 'Other / Want to know more'
  }
};

/* 目前語言（記在瀏覽器裡，下次開啟自動沿用） */
const DEFAULT_LANG = 'zh-Hant';
let currentLang = DEFAULT_LANG;

try {
  const saved = localStorage.getItem('iseda-lang');
  if (saved && I18N[saved]) currentLang = saved;
} catch (e) { /* 隱私模式等情況，忽略 */ }

/* 取翻譯文字 */
function t(key) {
  const dict = I18N[currentLang] || I18N[DEFAULT_LANG];
  return dict[key] || I18N[DEFAULT_LANG][key] || key;
}

/* 套用語言 */
function applyLang(lang) {
  if (!I18N[lang]) return;
  currentLang = lang;
  try { localStorage.setItem('iseda-lang', lang); } catch (e) {}
  document.documentElement.lang = lang;

  // 一般文字
  document.querySelectorAll('[data-i18n]').forEach(function (el) {
    const key = el.getAttribute('data-i18n');
    if (el.hasAttribute('data-i18n-html')) {
      el.innerHTML = t(key);
    } else {
      el.textContent = t(key);
    }
  });

  // placeholder
  document.querySelectorAll('[data-i18n-placeholder]').forEach(function (el) {
    el.placeholder = t(el.getAttribute('data-i18n-placeholder'));
  });

  document.querySelectorAll('[data-i18n-aria-label]').forEach(function (el) {
    el.setAttribute('aria-label', t(el.getAttribute('data-i18n-aria-label')));
  });

  // 頁面標題
  document.querySelectorAll('[data-i18n-title]').forEach(function (el) {
    el.textContent = t(el.getAttribute('data-i18n-title'));
  });

  // 語言按鈕狀態
  document.querySelectorAll('.lang-btn').forEach(function (btn) {
    btn.classList.toggle('active', btn.getAttribute('data-lang') === lang);
  });

  // 通知其他腳本（例如 script.js 的提示訊息）
  document.dispatchEvent(new CustomEvent('langchange', { detail: lang }));
}

/* 綁定語言切換按鈕 */
document.addEventListener('DOMContentLoaded', function () {
  document.querySelectorAll('.lang-btn').forEach(function (btn) {
    btn.addEventListener('click', function () {
      applyLang(btn.getAttribute('data-lang'));
    });
  });
  applyLang(currentLang);
});
